"use client"

import { Excalidraw } from "@excalidraw/excalidraw"
import "@excalidraw/excalidraw/index.css"

const INITIAL_ELEMENTS = [
  {
    id: "root",
    type: "rectangle",
    x: 300,
    y: 200,
    width: 180,
    height: 60,
    strokeColor: "#1c1c1c",
    backgroundColor: "#fafafa",
    fillStyle: "solid",
    strokeWidth: 2,
    roundness: { type: 2, value: 12 },
    text: "视频主题",
  },
  {
    id: "background",
    type: "rectangle",
    x: 560,
    y: 80,
    width: 160,
    height: 50,
    strokeColor: "#1c1c1c",
    backgroundColor: "#e8f4fc",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 2, value: 10 },
    text: "背景与现状",
  },
  {
    id: "concepts",
    type: "rectangle",
    x: 560,
    y: 170,
    width: 160,
    height: 50,
    strokeColor: "#1c1c1c",
    backgroundColor: "#fef3c7",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 2, value: 10 },
    text: "关键概念",
  },
  {
    id: "cases",
    type: "rectangle",
    x: 560,
    y: 260,
    width: 160,
    height: 50,
    strokeColor: "#1c1c1c",
    backgroundColor: "#dcfce7",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 2, value: 10 },
    text: "案例分析",
  },
  {
    id: "methods",
    type: "rectangle",
    x: 560,
    y: 350,
    width: 160,
    height: 50,
    strokeColor: "#1c1c1c",
    backgroundColor: "#f3e8ff",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 2, value: 10 },
    text: "方法与技巧",
  },
  {
    id: "history",
    type: "rectangle",
    x: 800,
    y: 40,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#e8f4fc",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "历史背景",
  },
  {
    id: "current-state",
    type: "rectangle",
    x: 800,
    y: 100,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#e8f4fc",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "当前状态",
  },
  {
    id: "definition",
    type: "rectangle",
    x: 800,
    y: 130,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#fef3c7",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "核心定义",
  },
  {
    id: "principles",
    type: "rectangle",
    x: 800,
    y: 190,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#fef3c7",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "基本原理",
  },
  {
    id: "case1",
    type: "rectangle",
    x: 800,
    y: 220,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#dcfce7",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "案例一",
  },
  {
    id: "case2",
    type: "rectangle",
    x: 800,
    y: 280,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#dcfce7",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "案例二",
  },
  {
    id: "tip1",
    type: "rectangle",
    x: 800,
    y: 310,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#f3e8ff",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "技巧一",
  },
  {
    id: "tip2",
    type: "rectangle",
    x: 800,
    y: 370,
    width: 120,
    height: 40,
    strokeColor: "#1c1c1c",
    backgroundColor: "#f3e8ff",
    fillStyle: "solid",
    strokeWidth: 1,
    roundness: { type: 2, value: 8 },
    text: "技巧二",
  },
  {
    id: "edge-root-background",
    type: "arrow",
    x: 480,
    y: 220,
    width: 80,
    height: 40,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, -40]],
    startBinding: { elementId: "root", focus: 0.5, gap: 1 },
    endBinding: { elementId: "background", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-root-concepts",
    type: "arrow",
    x: 480,
    y: 230,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "root", focus: 0.5, gap: 1 },
    endBinding: { elementId: "concepts", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-root-cases",
    type: "arrow",
    x: 480,
    y: 260,
    width: 80,
    height: 40,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 40]],
    startBinding: { elementId: "root", focus: 0.5, gap: 1 },
    endBinding: { elementId: "cases", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-root-methods",
    type: "arrow",
    x: 480,
    y: 290,
    width: 80,
    height: 80,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 2,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 80]],
    startBinding: { elementId: "root", focus: 0.5, gap: 1 },
    endBinding: { elementId: "methods", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-bg-history",
    type: "arrow",
    x: 720,
    y: 90,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "background", focus: 0.5, gap: 1 },
    endBinding: { elementId: "history", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-bg-current",
    type: "arrow",
    x: 720,
    y: 110,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "background", focus: 0.5, gap: 1 },
    endBinding: { elementId: "current-state", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-concepts-definition",
    type: "arrow",
    x: 720,
    y: 185,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "concepts", focus: 0.5, gap: 1 },
    endBinding: { elementId: "definition", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-concepts-principles",
    type: "arrow",
    x: 720,
    y: 205,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "concepts", focus: 0.5, gap: 1 },
    endBinding: { elementId: "principles", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-cases-case1",
    type: "arrow",
    x: 720,
    y: 275,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "cases", focus: 0.5, gap: 1 },
    endBinding: { elementId: "case1", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-cases-case2",
    type: "arrow",
    x: 720,
    y: 295,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "cases", focus: 0.5, gap: 1 },
    endBinding: { elementId: "case2", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-methods-tip1",
    type: "arrow",
    x: 720,
    y: 365,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "methods", focus: 0.5, gap: 1 },
    endBinding: { elementId: "tip1", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
  {
    id: "edge-methods-tip2",
    type: "arrow",
    x: 720,
    y: 385,
    width: 80,
    height: 0,
    strokeColor: "#9ca3af",
    backgroundColor: "transparent",
    fillStyle: "solid",
    strokeWidth: 1.5,
    roundness: { type: 0, value: 0 },
    text: "",
    points: [[0, 0], [80, 0]],
    startBinding: { elementId: "methods", focus: 0.5, gap: 1 },
    endBinding: { elementId: "tip2", focus: 0.5, gap: 1 },
    endArrowhead: "arrow",
  },
]

export function MindMap() {
  return (
    <div className="relative w-full h-full bg-[#fafafa]">
      <Excalidraw
        initialData={{
          elements: INITIAL_ELEMENTS as any,
          appState: {
            viewBackgroundColor: "#fafafa",
          },
        }}
        onChange={() => {}}
      />
    </div>
  )
}